export { 공지소식사항 } from './공지소식사항'
export { 공지소식사항Link1 } from './공지소식사항Link1'
export { 갤러리 } from './갤러리 components/갤러리'
// export { BadmintonPhotos } from './갤러리 components/photos/BadmintonPhotos'
// export { BasketballPhotos } from './갤러리 components/photos/BasketballPhotos'
// export { GroupPhotos } from './갤러리 components/photos/GroupPhotos'
// export { HockeyPhotos } from './갤러리 components/photos/HockeyPhotos'
// export { ElectionPhotos } from './갤러리 components/photos/ElectionPhotos'
// export { PoolPhotos } from './갤러리 components/photos/PoolPhotos'
// export { SoccerPhotos } from './갤러리 components/photos/SoccerPhotos'
// export { SwimmingPhotos } from './갤러리 components/photos/SwimmingPhotos'
// export { TennisPhotos } from './갤러리 components/photos/TennisPhotos'
// export { TrophyPhotos } from './갤러리 components/photos/TrophyPhotos'
// export { 갤러리Vid1 } from './갤러리 components/videos/갤러리Vid1'
